version: "3"
services:
  app:
    hostname: app
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    env_file:
      - .env
      - .env.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - gems:/app/vendor/bundle
      - node_modules:/app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - default

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - default

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/cache:/data
    networks:
      - default

volumes:
  gems:
  node_modules:
  postgresql:
  redis:
